import { Mobile } from '../types/mobile';
import { Accessory } from '../types/accessory';

export const INITIAL_MOBILES: Mobile[] = [
  { 
    id: 'mob_001', 
    brand: 'Apple', 
    model: 'iPhone 15 Pro Max', 
    imei: '354890123456789', 
    color: 'Titanium Natural', 
    storage: '256GB', 
    ram: '8GB',
    battery: '100%',
    condition: 'Brand New',
    boughtFrom: 'Main Distributor',
    purchaseDate: '2024-02-10',
    currency: 'USD',
    buyPrice: 1050, 
    sellPrice: 1199, 
    accessories: 'All',
    notes: 'Factory sealed, 1 year Apple official warranty.',
    status: 'in_stock',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString()
  },
  { 
    id: 'mob_002', 
    brand: 'Samsung', 
    model: 'Galaxy S24 Ultra', 
    imei: '354890123456790', 
    color: 'Titanium Black', 
    storage: '512GB', 
    ram: '12GB',
    battery: '100%',
    condition: 'Brand New',
    boughtFrom: 'Dubai Wholesale Hub',
    purchaseDate: '2024-02-12',
    currency: 'USD',
    buyPrice: 1120, 
    sellPrice: 1299, 
    accessories: 'Cable and Carton',
    notes: 'Includes S-Pen, Middle East Spec with dual physical SIM.',
    status: 'in_stock',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString()
  },
  { 
    id: 'mob_003', 
    brand: 'iPad / Tablet', 
    model: 'iPad Pro 12.9" M2', 
    imei: 'DMPZK099Q16R', 
    color: 'Space Gray', 
    storage: '256GB', 
    ram: '8GB',
    battery: '98%',
    condition: 'Mint (Used)',
    boughtFrom: 'Customer Trade-in',
    purchaseDate: '2024-01-20',
    currency: 'USD',
    buyPrice: 780, 
    sellPrice: 920, 
    accessories: 'Only Cable',
    notes: 'Flawless screen with tempered glass installed.',
    status: 'in_stock',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  { 
    id: 'mob_004', 
    brand: 'Apple', 
    model: 'iPhone 13', 
    imei: '354890123456791', 
    color: 'Midnight', 
    storage: '128GB', 
    ram: '4GB',
    battery: '88%',
    condition: 'Good (Used)',
    boughtFrom: 'Customer Trade-in',
    purchaseDate: '2023-11-10',
    currency: 'USD',
    buyPrice: 420, 
    sellPrice: 550, 
    accessories: 'Cable and Adapter',
    notes: 'Minor scuff on lower bezel, camera 100% clean.',
    status: 'sold',
    soldDate: '2024-02-14',
    soldPrice: 540,
    soldToCustomer: 'Ahmed Al-Kurdi (0750 445 1289)',
    soldNotes: 'Sold with 1 month store warranty.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  { 
    id: 'mob_005', 
    brand: 'Xiaomi', 
    model: '14 Pro', 
    imei: '354890123456792', 
    color: 'White Ceramic', 
    storage: '256GB', 
    ram: '12GB',
    battery: '100%',
    condition: 'Brand New',
    boughtFrom: 'Regional Distributor',
    purchaseDate: '2024-01-28',
    currency: 'USD',
    buyPrice: 740, 
    sellPrice: 880, 
    accessories: 'All',
    notes: 'HyperOS Global ROM, 120W fast charger included in box.',
    status: 'in_stock',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString()
  },
  { 
    id: 'mob_006', 
    brand: 'iPad / Tablet', 
    model: 'iPad Air 5th Gen (M1)', 
    imei: 'H39F08LLP9', 
    color: 'Purple', 
    storage: '64GB', 
    ram: '8GB',
    battery: '94%',
    condition: 'Good (Used)',
    boughtFrom: 'Wholesale Trade',
    purchaseDate: '2023-12-15',
    currency: 'USD',
    buyPrice: 410, 
    sellPrice: 510, 
    accessories: 'Only Carton',
    notes: 'Sold to repeat customer with paperless invoice.',
    status: 'sold',
    soldDate: '2024-02-18',
    soldPrice: 500,
    soldToCustomer: 'Sara Mohammed (0770 198 8734)',
    soldNotes: 'Payment in Cash USD.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString()
  }
];

export const INITIAL_ACCESSORIES: Accessory[] = [
  {
    id: 'acc_001',
    name: 'Apple 20W USB-C Power Adapter',
    brand: 'Apple',
    category: 'Chargers & Cables',
    barcode: '194252157007',
    sku: 'MHJE3ZM/A',
    quantity: 24,
    buyPrice: 14,
    sellPrice: 22,
    currency: 'USD',
    company: 'Al-Madar Tech',
    location: 'Drawer A1',
    notifyThreshold: 5,
    status: 'in_stock',
    compatibility: 'iPhone 12/13/14/15/iPad',
    totalSold: 112,
    notes: 'Original Foxconn batch, sealed box',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 86400000).toISOString()
  },
  {
    id: 'acc_002',
    name: 'Anker 323 Power Bank (10,000mAh 12W)',
    brand: 'Anker',
    category: 'Power Banks',
    barcode: '0194644118938',
    sku: 'A1236H11',
    quantity: 12,
    buyPrice: 18,
    sellPrice: 28,
    currency: 'USD',
    company: 'Anker Kurdistan',
    location: 'Shelf B2',
    notifyThreshold: 3,
    status: 'in_stock',
    compatibility: 'Universal (USB-C & USB-A)',
    totalSold: 45,
    notes: '18 Months official local warranty',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 86400000).toISOString()
  },
  {
    id: 'acc_003',
    name: 'iPhone 15 Pro MagSafe Clear Case',
    brand: 'Apple',
    category: 'Cases & Covers',
    barcode: '195949038221',
    sku: 'MT223ZM/A',
    quantity: 18,
    buyPrice: 8,
    sellPrice: 18,
    currency: 'USD',
    company: 'Smart Accessories LLC',
    location: 'Display Stand 1',
    notifyThreshold: 4,
    status: 'in_stock',
    compatibility: 'iPhone 15 Pro',
    totalSold: 88,
    notes: 'High clarity anti-yellowing TPU',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 86400000).toISOString()
  },
  {
    id: 'acc_004',
    name: 'Green Lion 9H HD Screen Protector (2-Pack)',
    brand: 'Green Lion',
    category: 'Screen Protectors',
    barcode: '6935100720441',
    sku: 'GN-SCRN-15PM',
    quantity: 35,
    buyPrice: 3,
    sellPrice: 8,
    currency: 'USD',
    company: 'Green Lion Official',
    location: 'Glass Rack C3',
    notifyThreshold: 10,
    status: 'in_stock',
    compatibility: 'iPhone 15 Pro Max',
    totalSold: 240,
    notes: 'Includes auto-alignment installation tray',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 86400000).toISOString()
  },
  {
    id: 'acc_005',
    name: 'Samsung 45W Super Fast Charger 2.0',
    brand: 'Samsung',
    category: 'Chargers & Cables',
    barcode: '8806094285112',
    sku: 'EP-T4510XBEGWW',
    quantity: 8,
    buyPrice: 22,
    sellPrice: 35,
    currency: 'USD',
    company: 'Dubai Wholesale Hub',
    location: 'Drawer A2',
    notifyThreshold: 3,
    status: 'in_stock',
    compatibility: 'Galaxy S24 Ultra / S23 / Tab S9',
    totalSold: 67,
    notes: 'Includes 5A Type-C to Type-C cable',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString()
  }
];
